version: "3"

services:
  opencanary:
    build:
      context: .
      network: host
    container_name: opencanary
    hostname: opencanary
    ports:
      - "22:22"
      - "80:80"
      - "3306:3306"
    volumes:
      - ./data/root:/root
      - ./data/log:/var/log/opencanary
    restart: unless-stopped
